language: php
services:
  - mysql
php:
  - '7.1'
before_install:
  - sudo apt-get update
  - sudo apt-get install graphviz
  - mysql -e 'CREATE DATABASE doctrineviz;'
install:
  - mv env/config/parameters.yml.dist env/config/parameters.yml
  - composer install
  - php env/console doctrine:schema:create
script:
  - phpunit --coverage-clover clover.xml
after_script:
  - php vendor/bin/coveralls -v
